import fs from "fs";
import ts from "typescript";
import { ChatOpenAI } from "@langchain/openai";
import { StateGraph, START, END } from "@langchain/langgraph";
import { ReviewStateAnnotation, ReviewState, FileReview } from "./state.js";
import { QA_REVIEW_PROMPT, FRAMEWORK_SUMMARY_PROMPT } from "./prompts.js";

const llm = new ChatOpenAI({
  model: "gpt-4o-mini",
  temperature: 0
});

function classifyFile(filePath: string): string {
  if (filePath.endsWith(".spec.ts")) {
    return "Playwright test spec file";
  }

  if (filePath.includes("Page") && filePath.endsWith(".ts")) {
    return "Page Object file";
  }

  if (filePath.includes("fixtures") && filePath.endsWith(".ts")) {
    return "Fixture file";
  }

  if (filePath.includes("ApiClient") && filePath.endsWith(".ts")) {
    return "API client file";
  }

  if (filePath.includes("ApiEndpoints") && filePath.endsWith(".ts")) {
    return "API endpoint constants file";
  }

  if (filePath.endsWith(".ts")) {
    return "TypeScript support file";
  }

  return "Unknown file type";
}

function getSyntaxDiagnostics(fileContent: string): string {
  const result = ts.transpileModule(fileContent, {
    compilerOptions: {
      module: ts.ModuleKind.NodeNext,
      target: ts.ScriptTarget.ES2022
    },
    reportDiagnostics: true
  });

  const diagnostics = result.diagnostics ?? [];

  if (diagnostics.length === 0) {
    return "No syntax issues found.";
  }

  return diagnostics
    .map((diagnostic) => {
      const message = ts.flattenDiagnosticMessageText(
        diagnostic.messageText,
        "\n"
      );

      return `TypeScript diagnostic ${diagnostic.code}: ${message}`;
    })
    .join("\n");
}

async function reviewAllFilesNode(
  state: ReviewState
): Promise<Partial<ReviewState>> {
  const reviews: FileReview[] = [];

  for (const filePath of state.filePaths) {
    const fileContent = fs.readFileSync(filePath, "utf-8");
    const fileType = classifyFile(filePath);
    const syntaxDiagnostics = getSyntaxDiagnostics(fileContent);

    const prompt = QA_REVIEW_PROMPT
      .replace("{syntaxDiagnostics}", syntaxDiagnostics)
      .replace("{code}", fileContent)
      .replace(
        "Review the following code carefully and avoid generic suggestions.",
        `Review the following ${fileType} carefully and avoid generic suggestions.`
      );

    const response = await llm.invoke(prompt);

    reviews.push({
      filePath,
      fileType,
      syntaxDiagnostics,
      reviewResult: response.content.toString()
    });
  }

  return {
    fileReviews: reviews
  };
}

async function generateFrameworkSummaryNode(
  state: ReviewState
): Promise<Partial<ReviewState>> {
  const fileReviewText = state.fileReviews
    .map((review, index) => {
      return `
File ${index + 1}: ${review.filePath}
File Type: ${review.fileType}
TypeScript Syntax Diagnostics:
${review.syntaxDiagnostics}

Review:
${review.reviewResult}
`;
    })
    .join("\n---\n");

  const prompt = FRAMEWORK_SUMMARY_PROMPT.replace("{reviews}", fileReviewText);

  const response = await llm.invoke(prompt);

  return {
    frameworkSummary: response.content.toString()
  };
}

async function generateFrameworkReportNode(
  state: ReviewState
): Promise<Partial<ReviewState>> {
  const reviewedFilesSection = state.fileReviews
    .map((review, index) => {
      return `
## ${index + 1}. File Reviewed

\`${review.filePath}\`

### File Type

${review.fileType}

### TypeScript Syntax Diagnostics

${review.syntaxDiagnostics}

${review.reviewResult}

---
`;
    })
    .join("\n");

  const report = `
# OrangeHRM AI QA Framework Review Report

## Overview

This report was generated by a LangGraph TypeScript QA review agent.

Note: This report is AI-assisted. Recommendations should be reviewed by an engineer before implementation.

The agent reviewed multiple Playwright TypeScript framework files and produced QA-focused feedback on:

- Playwright best practices
- Locator quality
- Assertion strength
- API validation quality
- Page Object Model usage
- Fixture usage
- Maintainability
- Reusability
- Flaky test risks

---

## Files Reviewed

${state.filePaths.map((filePath) => `- \`${filePath}\``).join("\n")}

---

# Framework-Level Summary

${state.frameworkSummary}

---

# File-Level Reviews

${reviewedFilesSection}
`;

  return {
    finalReport: report
  };
}

export function buildGraph() {
  const graph = new StateGraph(ReviewStateAnnotation)
    .addNode("reviewAllFiles", reviewAllFilesNode)
    .addNode("generateFrameworkSummary", generateFrameworkSummaryNode)
    .addNode("generateFrameworkReport", generateFrameworkReportNode)
    .addEdge(START, "reviewAllFiles")
    .addEdge("reviewAllFiles", "generateFrameworkSummary")
    .addEdge("generateFrameworkSummary", "generateFrameworkReport")
    .addEdge("generateFrameworkReport", END)
    .compile();

  return graph;
}